
name: Building and Pushing Archivy Container to DockerHub on manual workflow dispatch

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to deploy to Dockerhub
        required: true

jobs:
  dockerBuildPush:
    name: Build and push image with release version tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files from repository
        uses: actions/checkout@v2
        with:
          repository: sgc-sg0/archivy

      - name: Setting variables
        if: success()
        run: |
          date -u +'%Y-%m-%dT%H:%M:%SZ' > TIMESTAMP
          echo "${{ github.event.inputs.version }}" > VERSION
          echo "sgc003y" > DOCKER_USERNAME
          echo "docker.io/sgc003y/archivy" > DOCKER_IMAGE

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v1.0.2
        with:
          install: true
          version: latest

      - name: Docker login
        if: success()
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "$( cat DOCKER_USERNAME )" --password-stdin docker.io

      - name: Build and push with Docker Buildx
        if: success()
        run: |
          docker build \
            --output type=image,name="$( cat DOCKER_IMAGE )",push=true \
            --build-arg VERSION="$( cat VERSION )" --build-arg BUILD_DATE="$( cat TIMESTAMP )" \
            --tag "$( cat DOCKER_IMAGE ):$( cat VERSION )" \
            --file ./Dockerfile . \
          && docker build \
            --output type=image,name="$( cat DOCKER_IMAGE )",push=true \
            --build-arg VERSION="$( cat VERSION )" --build-arg BUILD_DATE="$( cat TIMESTAMP )" \
            --tag "$( cat DOCKER_IMAGE ):$( cat VERSION )-lite" \
            --file ./Dockerfile-light .
